# Generated by Django 4.1 on 2024-08-16 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        ("positon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contractModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaInicio", models.DateField()),
                ("fechaFin", models.DateField()),
                ("salarioDiario", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipoContrato",
                    models.CharField(
                        choices=[
                            ("Determinado", "Determinado"),
                            ("Indeterminado", "Indeterminado"),
                            ("Prestacion de servicios", "Prestacion de servicios"),
                            ("Capacitacion", "Capacitacion"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employemodel",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positon.positionmodel",
                    ),
                ),
            ],
        ),
    ]
