# Generated by Django 4.1 on 2024-08-16 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractmodel",
            name="puesto",
        ),
    ]
