# Generated by Django 4.1 on 2024-08-19 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0005_delete_employemodel_employee_model_puesto_and_more"),
        ("contract", "0003_alter_contractmodel_empleado"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="contractModel",
            new_name="contrato_model",
        ),
    ]
