# Generated by Django 4.1 on 2024-08-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("positon", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="employeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primerNombre", models.CharField(max_length=100)),
                ("segundoNombre", models.CharField(max_length=100)),
                ("apellidoMaterno", models.CharField(max_length=100)),
                ("apellidoPaterno", models.CharField(max_length=100)),
                (
                    "estadoCivil",
                    models.CharField(
                        choices=[
                            ("S", "Soltero"),
                            ("C", "Casado"),
                            ("D", "Divorciado"),
                            ("V", "Viudo"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")], max_length=100
                    ),
                ),
                ("nacionalidad", models.CharField(max_length=100)),
                ("fechaNacimiento", models.DateField()),
                ("calle", models.CharField(max_length=100)),
                ("colonia", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=100)),
                ("cp", models.CharField(max_length=100)),
                ("ciudad", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("pais", models.CharField(max_length=100)),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positon.positionmodel",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companymodel",
                    ),
                ),
            ],
        ),
    ]
