# Generated by Django 4.1 on 2024-08-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employemodel",
            name="estadoCivil",
            field=models.CharField(
                choices=[
                    ("Soltero", "Soltero"),
                    ("Casado", "Casado"),
                    ("Divorsiado", "Divorciado"),
                    ("Viudo", "Viudo"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employemodel",
            name="genero",
            field=models.CharField(
                choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                max_length=100,
            ),
        ),
    ]
