# Generated by Django 4.1 on 2024-08-19 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_alter_employemodel_estadocivil_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employemodel",
            name="calle",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="ciudad",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="colonia",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="cp",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="estadoCivil",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="fechaNacimiento",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="genero",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="nacionalidad",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="pais",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="puesto",
        ),
        migrations.RemoveField(
            model_name="employemodel",
            name="sucursal",
        ),
    ]
