# Generated by Django 4.1 on 2024-08-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "employee",
            "0003_remove_employemodel_calle_remove_employemodel_ciudad_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="employee_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primer_nombre", models.CharField(max_length=100)),
                ("segundo_nombre", models.CharField(max_length=100)),
                ("apellido_materno", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "genero",
                    models.CharField(
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        max_length=100,
                    ),
                ),
                ("nacionalidad", models.CharField(max_length=100)),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("Soltero", "Soltero"),
                            ("Casado", "Casado"),
                            ("Divorsiado", "Divorciado"),
                            ("Viudo", "Viudo"),
                        ],
                        max_length=100,
                    ),
                ),
                ("calle", models.CharField(default="Sin calle", max_length=100)),
                ("colonia", models.CharField(default="Sin calle", max_length=100)),
                ("numero", models.CharField(default="Sin calle", max_length=100)),
                ("cp", models.CharField(default="Sin calle", max_length=100)),
                ("ciudad", models.CharField(default="Sin ciudad", max_length=100)),
                ("estado", models.CharField(default="Sin calle", max_length=100)),
                ("pais", models.CharField(default="Sin calle", max_length=100)),
            ],
        ),
    ]
