# Generated by Django 4.1 on 2024-08-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0005_delete_employemodel_employee_model_puesto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee_model",
            name="calle",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee_model",
            name="ciudad",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee_model",
            name="colonia",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee_model",
            name="cp",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee_model",
            name="estado",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee_model",
            name="numero",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee_model",
            name="pais",
            field=models.CharField(max_length=100),
        ),
    ]
