# Generated by Django 4.1 on 2024-08-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0006_alter_employee_model_calle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee_model",
            name="segundo_nombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
