# Generated by Django 4.1 on 2024-08-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0007_alter_employee_model_segundo_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee_model",
            name="nacionalidad",
            field=models.CharField(
                blank=True, default="Mexicana", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="employee_model",
            name="pais",
            field=models.CharField(
                blank=True, default="México", max_length=100, null=True
            ),
        ),
    ]
