# Generated by Django 4.1 on 2024-08-15 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_remove_workstations_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="workstation",
        ),
        migrations.RemoveField(
            model_name="work_to_module",
            name="module",
        ),
        migrations.RemoveField(
            model_name="work_to_module",
            name="workstation",
        ),
        migrations.DeleteModel(
            name="modules",
        ),
        migrations.DeleteModel(
            name="users",
        ),
        migrations.DeleteModel(
            name="work_to_module",
        ),
        migrations.DeleteModel(
            name="workstations",
        ),
    ]
