# Generated by Django 5.1 on 2024-09-02 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0003_alter_typeincidentmodel_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="incidencias_proxy",
            fields=[],
            options={
                "verbose_name": "Registrar_Incidencia",
                "verbose_name_plural": "Registrar_Incidencias",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("incident.incidentmodel",),
        ),
    ]
