# Generated by Django 4.1 on 2024-08-19 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0005_delete_employemodel_employee_model_puesto_and_more"),
        ("branch", "0002_rename_branchmodel_empresa_model"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="companyModel",
            new_name="sucursal_model",
        ),
    ]
