# Generated by Django 4.1 on 2024-08-19 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("branch", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="branchModel",
            new_name="empresa_model",
        ),
    ]
